on:
  push:
    paths:
      - DESCRIPTION
      - .github/workflows/codemeta.yml
  workflow_dispatch:

name: Render codemeta

jobs:
  render:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'cm-skip')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::codemetar
          needs: codemeta

      - name: Render codemeta
        run: codemetar::write_codemeta()
        shell: Rscript {0}
    
      - name: Commit results
        run: |
          git commit codemeta.json -m 'Re-build codemeta.json [ci-skip]' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
